health_check_enabled: true
max_health_check_failures: 3
min_health_check_success: 3
health_check_frequency_in_seconds: 10
strategy: roundrobin
host: 0.0.0.0
port: 8080
servers:
  - name: host-1
    host: "http://localhost:8081"
  - name: host-2
    host: "http://localhost:8082"
  - name: host-3
    host: "http://localhost:8083"
